### PR TITLE
Shearing Demo

### PR DESCRIPTION
**Pull request by camden-bock**
I have finished a demo of the shearing triangle with two types of interactions with XR device input.  The line can be interacted with to reassign point c (the apex) of the triangle.  The other controller can be used to controll a cross-section plane for the triangle.

Their functionality has been tested in WebXR device emulator browser extension.

### CODE REVIEW

**Comment by camden-bock** [comment]
README.md has been updated to reflect use of WebXR emulator.

**Comment by camden-bock** [comment]
@Joey-Haney we should try the Oculus Quest in the emulator.

**Comment by Joey-Haney** [comment]
I have tested the Occulus Quest with the Shearing Triangle in the emulator. It works as expected, just as with the HTC vive.
Looking good in general.

**Review by Joey-Haney — COMMENTED** [review]
Whoops, accidentally only commented and closed.

**Review by Joey-Haney — APPROVED** [review]
Ok, See comments for my mild confusion.
Anyway, I will restate here:
Occulus quest works well.
Code looks good.
I give it a thumbs up.

**Pull request merged**
